# Generated by Django 2.2.3 on 2019-08-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0002_celltype_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='up_user',
            field=models.CharField(max_length=50, verbose_name='Upload User'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='datasearch.CellType'),
        ),
        migrations.AlterField(
            model_name='celltype',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_format',
            field=models.CharField(max_length=20, verbose_name='Data Format'),
        ),
        migrations.AlterField(
            model_name='data',
            name='disease_organ',
            field=models.CharField(max_length=100, verbose_name='Disease Type/Organ Type'),
        ),
        migrations.AlterField(
            model_name='data',
            name='n_samples',
            field=models.CharField(max_length=50, null=True, verbose_name='Number of Cells or Samples'),
        ),
        migrations.AlterField(
            model_name='data',
            name='seq_platform',
            field=models.CharField(max_length=100, null=True, verbose_name='Sequencing Platform'),
        ),
        migrations.AlterField(
            model_name='data',
            name='tech_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Sequencing Technology'),
        ),
    ]
