# Generated by Django 3.0.3 on 2020-06-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasearch', '0004_auto_20190810_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_type',
            field=models.CharField(max_length=50, verbose_name='Data Type'),
        ),
    ]
